### ISSUE TITLE
[Feature] Add smelting for gear into nuggets

### ISSUE THREAD

**Issue by Geethebluesky** [Noaaan/MythicMetals#106]
I'm not having any luck smelting armor made from your metals (copper, bronze in this case) back into nuggets or ingots. Since we can smelt iron and gold items in vanilla, in regular furnaces, I assume this is unintended?

In case it's important, I'm using wooden tools as fuel, not coal or anything (this is my scraps furnace).

Let me know what other info you need! Thanks.

**Comment by Noaaan** [comment]
I considered this at some point and I genuinely do not know if its actually worth adding hundreds of recipes for nuggets. 
In base MM no mobs spawn with gear, and you cannot find it in loot.
In practice the only time you would need to smelt it down is if you crafted it yourself and no longer want it. 
And Is it *really* worth spending fuel to get a singular bronze nugget?

**Comment by Geethebluesky** [comment]
I understand your point re: the work. I would like this for consistency's sake though (may be OCD talking).

I guess, would you be open to adding those recipes if someone else provides them? I might just end up making a datapack myself since well... in my view this is an easily-solved annoyance :) No offense intended, since I understand you're busy with other stuff.

**Comment by CamperSamu** [comment]
I think that if you want to contribute this way it would be accepted or at least it would be linked somewhere as a module for MM (idk I'm not Noaaan 👀)

**Comment by Noaaan** [comment]
Its not hard to make these recipes, its mainly a concern regarding performance.
Adding 200 smelting recipes for this should be fine, though it will in the long term, and I mean LOOONG term, make a ***tiny*** impact, which is why I am a bit reluctant to do this. 
This is not the decider though, as my bottom line is whether or not there is real demand for this, as its mostly a small QOL change in my eyes.

Ultimately I will consider doing this myself for next release, as nuggets are disable-able and will therefore need resource conditions.

**Comment by Noaaan** [comment]
Also I do need to note I would probably not backport this to 1.18.2. 
I recently made the final release for that version, and I wish to only maintain MM for the latest version of the game as of now.

**Comment by Geethebluesky** [comment]
Thanks for looking at this. I'm testing a datapack for 1.18.2 if anyone ever wants it besides me!
