### ISSUE TITLE
Custom rendered armor pieces incompatible with VanitySlots and SimpleHats

### ISSUE THREAD

**Issue by KuwuroUsagi** [Noaaan/MythicMetals#131]
Mythic Metal items using custom rendering don't accurately show/hide when using certain items intended to hide the model (Familiar Wig from VanitySlots, or any hat from SimpleHats)
I've experienced this only with the Metallurgium Helmet, but I've heard there could possibly be other pieces of armor of other metal variants that may use the same rendering process.

![javaw_2022-11-09_01-12-54](https://user-images.githubusercontent.com/6632311/200943285-de1cea1f-42f7-47b1-942a-6becafbf96fa.gif)

**Comment by Noaaan** [comment]
I am still looking into compatabilty with SimpleHats, but for Armor I would recommend using Cosmetic Armor instead: https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-fabric
Their implementation of the armor rendering is a bit simpler, and correctly overrides armor when worn in the slot.

**Comment by itsdinkd** [comment]
> I am still looking into compatabilty with SimpleHats, but for Armor I would recommend using Cosmetic Armor instead: https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-fabric Their implementation of the armor rendering is a bit simpler, and correctly overrides armor when worn in the slot.

Cosmetic  armor is very buggy and the developer doesnt really update it, ever. Check comments on modpage.

**Comment by Noaaan** [comment]
Hey, sorry for the long wait on a response on this issue. It ended up in my backlog, and frankly, after Nyako implementing support for VanitySlots I wrote this off as a non-issue, since I believe it is up to SimpleHats to implement support for Fabrics ArmorRenderer. I know a handful of mods use it, like Spectrum and Twilight Forest, so it would generally make more sense for them to fix it.
I also kinda like how the hats interact with the armor, so therefore I think its best to close this issue. Thanks for reporting!
![image](https://github.com/Noaaan/MythicMetals/assets/4163353/56f841d2-8da1-4399-9f40-55f49404c8f7)
