### ISSUE TITLE
Crash when accessing config

### ISSUE THREAD

**Issue by Kuggle01** [Noaaan/MythicMetals#132]
https://bytebin.lucko.me/EsPkbtp7Zc

**Comment by Noaaan** [comment]
This is a mod incompatability between owo-lib and ToolTip Fix. 
In owo-lib there is a system for displaying tooltips on components, which generates an Immutable List via a stream. Since tooltipfix does not check whether the list can be modified or not, it crashes when it tries to change the tooltip.
Feel free to quote me on this and open an issue there, if not I can open it for you

**Comment by Noaaan** [comment]
Should be fixed as of latest version of TooltipFix
