### ISSUE TITLE
Suggestion: Editable protection values in config

### ISSUE THREAD

**Issue by ereese99** [Noaaan/MythicMetals#155]
I have a modpack and some armor in those mods are easier to come by with better protection values. I wanted to maybe edit the values of the Mythic Metals armor in the config but it's just spawn rates. May you add that in?

**Comment by Noaaan** [comment]
Hey. Sorry for the long wait on a response. Generally this is not something I am planning to do in the short-term, as I believe it is more important for balancing to adjust the values from player feedback. 

From a modpack developer point of view: I do see the utility in being able to change these values, although I do want to note that the stats of Metallurgium Armor intentionally cap out vanilla Minecrafts armor limit of 30 armor points (*technically Metallurgium Armor gives 31 due to the leggings, but you get my point*). On the sidenote I do recognize some of the armor sets have sortoff lower values (Osmium and Aquarium in particular), which is being addressed in future patches. 

I would love to hear any feedback of what mods you are using together with MM, and what you are comparing it to. That way I could give you some better suggestions on how to handle this particular situation.
