### ISSUE TITLE
Crashing upon start

### ISSUE THREAD

**Issue by SpicyCake** [Noaaan/MythicMetals#159]
After adding mythical metals decorations the game crashes on start up.
Both mythic metals and the decorations are on 1.18.2 (latest on cursed forge for that version)
Below is crash report.
https://pastebin.com/vJgREkVC

**Comment by Noaaan** [comment]
I believe this is due to the 0.16.x line of Mythic Metals was backported while Decorations was never really patched to work with it correctly. If you wish to use Decorations I recommend downgrading Mythic Metals to 0.14.4, as that is the latest version that works with Decorations. 
I currently have no plans on backporting it. I will let you know if I ever change my mind, but for now I will simply close this issue.
