### ISSUE TITLE
[Balance suggestion] MM axes are too weak as weapons

### ISSUE THREAD

**Issue by drown3d** [Noaaan/MythicMetals#163]
When used for combat or butchering, the vanilla axes are pretty balanced (not counting enchantments), but the axes from mythic metals feel much weaker. For example, why should a steel axe only deal 7.5 attack damage when an iron axe deals 9 (assuming the same attack speed)?

Proposed solution: increase all axes' attack damage by 1.5

**Comment by Noaaan** [comment]
Hey, sorry for the long time without a response. You have not been ignored! Generally this question has brewed on my mind the last few weeks, and after consideration I do agree that the axes need some changes.

The reasoning behind the original axe damage values are because they are not strictly balanced around vanilla - They are only balanced around the high tier axes (diamond & netherite), since it is my belief that the other axes are NOT balanced. I mean come on, a Stone Axe gives you a +4 damage increase compared to a sword? Ridiculous.

Because of this the lower tier axes suffered, but as of 0.18.0 all axes will have the same treatment across the board (+2 damage over its sword). I believe this is the best approach as all the high-tier axes already have this treatment, and are more than sufficient weapons (for example adamantite, which is designed to be crafted into weapons). 

Thank you for opening an issue regarding this. Hopefully you understand why I make the changes this way.
