### ISSUE TITLE
mythic metals and levelz compatibility?

### ISSUE THREAD

**Issue by ToXi4eK12** [Noaaan/MythicMetals#197]
i have armor and item from mythic metals,and i have levelz but armor and items do not require level from levelz.Is there anything  can do about it?

**Comment by Noaaan** [comment]
This is something you or I would want to implement via a datapack in order to apply the restrictions correctly. While most of the pre/post diamond ores would fit into levelling, and might even be fun to design, I do think the post-netherite items (Adamantite, Mythril, Orichalcum, Unobtainium alloys, etc.) Is not that great, as you would need to lock it all at level 20. 

If LevelZ has a way to increase the level cap for a skill then it is a different story, but that is best on a modpack level to design. For now this is something I won't work on, albeit I am open to suggestions for level gaps for lower tier stuff.
