### ISSUE TITLE
Can't find recipes

### ISSUE THREAD

**Issue by CryoNine** [Noaaan/MythicMetals#205]
I've searched everywhere, even here, but I can't find anything that tells me what the recipes for the tools and items are. I had go into creative mode to get the forge block, and the ingots form no armors or tools. There are no real guides for this anywhere.

**Comment by Noaaan** [comment]
In the latest version of Mythic Metals - Every single material that can be crafted into both armor and tools (with one exception) are present in the Advancements of the mod. The recipes for all the alloys are present in these as well, written out in plain text. The advancement screen also includes information on how to obtain Smithing Templates, which are required for specific gear and weapons. You should automatically unlock the recipes for these (recipe book) when picking up the relevant material to the craftable Smithing Templates. Any material that is a catalyst, which cannot be crafted into anything alone, is NOT present in the Advancements. This is by design. 

![image](https://github.com/Noaaan/MythicMetals/assets/4163353/4046945d-3bc0-4fdf-b473-1ce15522f961)

*note that this exact screenshot is from a future beta of Mythic Metals, which is why there is different textures and advancements*

In regards to Alloy Forgery, I believe any information you would need as an end-user is on the mod page itself:  https://legacy.curseforge.com/minecraft/mc-mods/alloy-forgery

**Comment by CryoNine** [comment]
> In the latest version of Mythic Metals - Every single material that can be crafted into both armor and tools (with one exception) are present in the Advancements of the mod. The recipes for all the alloys are present in these as well, written out in plain text. The advancement screen also includes information on how to obtain Smithing Templates, which are required for specific gear and weapons. You should automatically unlock the recipes for these (recipe book) when picking up the relevant material to the craftable Smithing Templates. Any material that is a catalyst, which cannot be crafted into anything alone, is NOT present in the Advancements. This is by design.
> 
> ![image](https://user-images.githubusercontent.com/4163353/282253346-4046945d-3bc0-4fdf-b473-1ce15522f961.png)
> 
> _note that this exact screenshot is from a future beta of Mythic Metals, which is why there is different textures and advancements_
> 
> In regards to Alloy Forgery, I believe any information you would need as an end-user is on the mod page itself: 

Thank 🍞👍🏻
