### ISSUE TITLE
[Quilt] Unable to connect to server due to mismatched states

### ISSUE THREAD

**Issue by Venaf** [Noaaan/MythicMetals#206]
## Mismatched states for entries of 'minecraft:block'
   - Found 'mythicmetals:adamantite_block', expected 'alloy_forgery:adamantite_block_forge_controller'
   - Found 'alloy_forgery:adamantite_block_forge_controller', expected 'mythicmetals:adamantite_block'

Minecraft 1.20.1 with Quilt Loader 0.21.1

Alloy Forgery 2.0.22+1.20
Mythic Metals 0.18.2+1.20
[mod list gist](https://gist.github.com/Venaf/300b753e0cde083a156e49564f3b8f2a)

Getting this when trying to connect to a custom mod list.  Not sure if the issue is actually with these mods, I've not run into this in the past.

Mods work fine in single player and the server seems to be running fine, just can't connect.

**Comment by Noaaan** [comment]
This issue is unfortunately a Quilt exclusive problem, which you see with these related issues: #180 #182 

There is already an issue open for this on QFAPI's repository (https://github.com/QuiltMC/quilted-fabric-api/issues/115). The summary of it is that it seems to be a load-order dependent issue that is problematic specifically with Quilt Registry Sync in some way. 

As mentioned previously in the related issues; I am still unable to reproduce this myself, and I do not know what the best methods are to debug it. I do know that from experience that enabling/disabling random mods can change the load order to the point where this issue doesn't appear anymore, but it is still a very annoying incompatibility.

**Comment by Noaaan** [comment]
Going forward I will not be supporting Quilt, as from what I have read they are diverging QFAPI to be it's own thing. While I might look into porting in the future, it is not a priority as of now.
