### ISSUE TITLE
[Feature Request] Make Mythic Metals not hard-dependent on Alloy Forgery

### ISSUE THREAD

**Issue by KonSola5** [Noaaan/MythicMetals#208]
This change would allow pack makers to add Mythic Metals even if Alloy Forgery just does not fit the pack very well.

The pack autor or an addon maker must then take care of adding recipes, since those are added using Alloy Forgery.
So there should be a **clear** warning in game chat and logs that Alloy Forgery is not installed, and thus recipes are not craftable by default.
The warning could then be disabled in config.

**Comment by Dragon-Seeker** [comment]
The Idea of such sounds reasonable but may raise more confusion and issues. The idea that "...Alloy Forgery just does not fit the pack..." seems quite odd since it's just a souped-up Blast Furnace after all and fits the idea of alloy crafting that MM is based on.

Furthermore, it would then be problematic since there would be a reliance on Modpack Authors and Addon Creatators to implement the needed recipes which would lead to a harder time helping others with methods for getting the various items from the mod if they are not willing to use AF within the pack.

**Comment by KonSola5** [comment]
Hence the need of a warning in chat.
For example, here's what happens when you install Modern Industrialization without a recipe viewer - there's a clear warning in chat, but it's not hard-dependent on JEI/REI/EMI present.
![warning](https://github.com/Noaaan/MythicMetals/assets/125081901/70bc9199-cb47-47a3-9c92-825a14d618dd)

The warning is also dismissable in their config:
![config](https://github.com/Noaaan/MythicMetals/assets/125081901/fb376eef-a380-488c-9977-00f982780499)

**Comment by Noaaan** [comment]
This is technically possible to do, but it is certainly something I would only leave to advanced players or pack devs. In my eyes the definitive experience with Mythic Metals relies on Alloy Forgery, and the biggest hurdle for decoupling is that I do not want to leave it out of the dependencies (in the fabric.mod.json metadata file). 
I could certainly make a wiki-page with info on how to override the FMJ specifically for MM, and maybe some load conditions to be able to surpress errors regarding this, although it is not something I will prioritize at the moment.
