### ISSUE TITLE
Enchanted Midas Gold Block not dropping

### ISSUE THREAD

**Issue by DavixAF** [Noaaan/MythicMetals#211]
Sorry if bad english.
Im playing in version ([1.20+] Mythic Metals - 0.18.2) of the mod in fabric 1.20.1
im trying to upgrade the gilded midas gold sword.
I dont know if its bad luck or am i doing something wrong but i have trade more than 30 stacks of midas gold ingots with piglins. I HAVE RECEIVED 3 UNNOBTANIUM AND NO ENCHANTED MIDAS GOLD BLOCK, so ive been wondering if im doing something wrong or is it an issue of the mod.

edit: also it doesnt drop the royal midas gold sword template, so its still the same if youre wondering
thanks

**Comment by Noaaan** [comment]
Hey, thanks for opening this issue.
Yes, there is definitely something off with the Enchanted Midas Gold Block drop-rates, as well as Unobtainium accidentally being added twice to the Loot Table. Looking into it it simply seems that the loot method used is simply too rare, as it involves two actions:
- Hit the Enchanted Midas Gold Block on the Loot Table
- Pass a RNG check on whether you receive the block. On a fail it rerolls. 

Problem lies in the second check, as combined with just hitting the drop table in general it proves to be way too rare. After doing some testing I will increase the drop rate greatly for the next patch. You should hopefully be able to expect a block or two every 640 rolls (10 stacks). 

The Template is also not dropped from them, it is crafted from the Enchanted Midas Gold Block. ~~You should receive the recipe on pickup of the block, Check your recipe book~~ Turns out this is also not functional at the moment 🫠 The recipe is still mentioned in the Advancements though. Alternatively I recommend to install a mod like Roughly Enough Items.

**Comment by Noaaan** [comment]
Should be fixed with cde358af4987fe291fca0bc3b2b2d9a64b3a3e7c

**Comment by DavixAF** [comment]
1.Thank you, i think i was going insane for the drop rate, now i can stop wasting midas gold and keep doing other things until its solved.

2. oh well, i misunderstood then. 

The advancement "A True Noble Swordsmith" says: "Barter with midas gold until you get a Royal Midas Gold Template" ... i knew that the EMGB was a part of the recipe, but i said to myself: maybe theres a low chance they give it to you directly.

I think maybe changing the order of the advancements, because i saw in another issue, a screenshot of the advancements, and there was an advancement for getting the EMGB AFTER the template. Or maybe changing the description, idk.

3. thank you for this mod, its one of my favorites, so many details and unique abilities, i dont know much about coding but i bet thats a lot of work.

**Comment by Noaaan** [comment]
> The advancement "A True Noble Swordsmith" says: "Barter with midas gold until you get a Royal Midas Gold Template" ... i knew that the EMGB was a part of the recipe, but i said to myself: maybe theres a low chance they give it to you directly.

I think that has been fixed for a while, just not released quite yet. It should be in the alpha though!

![image](https://github.com/Noaaan/MythicMetals/assets/4163353/cd7cc196-0dfa-4f51-9e42-f84749a08c23)

**Comment by DavixAF** [comment]
OOOH i just saw how to change the json of better pigling barter, THANK YOU... youre amazing, so fast. sorry didnt know about the advancement, i downloaded the July 14 version of curseforge and it said that... well, anyway, sorry for bothering.

**Comment by Noaaan** [comment]
Not at all, this proved to be a very useful bug report. Happened to catch me at a great time where I could properly sit down and look into it too 😄
