### ISSUE TITLE
[Feature Request] Alloy Forgery JEI Compatability 

### ISSUE THREAD

**Issue by ChaoscatCJ** [Noaaan/MythicMetals#217]
[feature request] could you please make it to where you can find the recipes for the alloys for armors and weapons.They dont even show up in JEI the only way i can get them is the creative menu and even then thats just cheating the item in

**Comment by Noaaan** [comment]
Issues with Alloy Forgery recipes should be opened in the [Alloy Forgery repository](https://github.com/wisp-forest/alloy-forgery). ~~I have gone ahead and transferred this issue there.~~ edit: nevermind, seems I am unable to. 
Currently JEI is not supported due to issues getting it to build in the AF Fabric environment, as well as this issue: https://github.com/wisp-forest/owo-lib/issues/177
For now I recommend using one of the other recipe viewer alternatives, like Roughly Enough Items or EMI.
