### ISSUE TITLE
It's `Snoop Dogg`, with *two* `g`s.

### ISSUE THREAD

**Issue by SubordinalBlue** [Noaaan/MythicMetals#239]
![image](https://github.com/Noaaan/MythicMetals/assets/6677700/0eb16bbc-54a0-45b8-a3de-352edad2c4ea)

![](https://upload.wikimedia.org/wikipedia/en/a/a3/Tha-doggfather.jpg)

**Comment by Noaaan** [comment]
While investigating this somewhat **critical** issue, I do not know how to fully go ahead and solve this.
Adding two G's to "The Dog" would make the item reference [The Dogg](https://en.wikipedia.org/wiki/The_Dogg), who is a different musician. My first thought was then to rename the item to "Tha Dogg", which turns out, is [a rapper group](https://en.wikipedia.org/wiki/Tha_Dogg_Pound) (who have worked with Snoop in the past). 
As such, I will label this appropriately
