### ISSUE TITLE
Texture suggestions.

### ISSUE THREAD

**Issue by K0-RR** [Noaaan/MythicMetals#34]
- new Aquarium, Quadrillum (texture is "too big" my gah), Unobtainium (it's "too small", I hate my engrish) and Starrite texture (Banglum/Kyber/Zinc/Tantalite/Runite/Vermiculite/Carmot recolored?) (what about renaming it too? To something from real life)
- Mirror vertically/horizontally or rotate by 90/180/270 degrees the textures of Osmium, Platinum, Tin, Silver, Manganese, Vermiculite, Ur, and **Stormyx**
- Use official (from 1.17 snapshots) copper texture.
- Tantalite has a nice texture design but is nearly invisible because of its colors
- Oh yea and steal the "texture paterns" from 1.17 snapshots ores

**So it would look like this:**
- Ores that use vanilla design pattern would be rotated or mirrored
- Ores with bad textures (invisible or just not as good as the rest) would use some recolored 1.17 textures
- The copper texture is changed to the vanilla one

Are You okay with this?

**Comment by Noaaan** [comment]
I believe I have had enough time to ponder on these points you have presented.

- I might look into tweaking the quadrillum texture a bit, though I am happy with both banglum, kyber and aquarium and I have not planned changing these. When it comes to the rest of the ores mentioned I agree they need an overhaul, and they will recieve one in the future. Renaming ores in Mythic Metals is a bit scary to do, simply as you would lose items upon doing so. While I originally used a lot of real-life names for ores I decided to move away from that direction, simply due to the lack of variety in colours with a lot of real life ores. 
- In the current state of the textures I do not believe rotating vanilla-based textures will have a good result when it comes to textures. These ores will at some point recieve overhauls, and considering that vanilla Minecraft is giving every ore a new design, so should Mythic Metals. The reason behind the changes in the first place is accessibility, and also some of these re-uses will become unique once 1.17 rolls around (I.E. Stormyx, since it uses the old emerald ore texture).
- Copper ores/blocks is currently planned to be dropped after 1.17. There is no reason to have multiple copper ores if the vanilla game supports it. I will still keep in copper tools/armor.
- As said earlier, due to the fact that new texture patterns try to be unique for accesibility it does not make sense to re-use these. The style is really interesting though, I will look into creating even more ore variants around these.    

Currently im busy with Alloy Forgery and school-duties, and the artist working on the ore textures has been busy. I have an update planned though, and I will see if I can ship more textures once it releases.

**Comment by Noaaan** [comment]
As of commit 8683178fcd4629b532ea1639dfb6ef985440db29 all ores now have somewhat of an unique texture. 
They will be tweaked in the future, but for now I consider this issue closed.
