### ISSUE TITLE
Constant Server Spam

### ISSUE THREAD

**Issue by SHXRKIEgg** [Noaaan/MythicMetals#46]
Hi, I'm trying to add your mod to my Medieval Pack and when I enter the nether on a server this constantly spams every split second.

[06:48:32] [Worker-Main-7/WARN]: Empty height range: [50 absolute-100 below top]

This could be an incompatibility with Caves and Cliffs add-on for William Wythers' Overworld?

**Comment by Noaaan** [comment]
Considering the disclaimer on WWO's CurseForge site I would deem it likely. I will look more into this issue.

**Comment by SHXRKIEgg** [comment]
Yeah just saw that too. Will be really awesome to make it compatible as it looks like a cool mod to add to my Modpack

**Comment by SHXRKIEgg** [comment]
Hi has this been fixed?

**Comment by Noaaan** [comment]
Thanks for bumping! I sadly have not found the time to fix this issue yet, but I do believe I have identified it. 

It is a range issue with Starrite trying to spawn in the nether, but failing due to the top of the nether ore spawning range being 128 [since the top offset is 100 from y=128, it overlaps with the minimum height of 50, making it impossible to spawn]

Could you try to set the top offset of normal starrite to 20 in the config file? That and/or adding the nether biomes to the overworld ore blacklist should do the trick.
