### ISSUE TITLE
Nether Ore in 1.18.1

### ISSUE THREAD

**Issue by itsdinkd** [Noaaan/MythicMetals#53]
What happens if nether ore (palladium) has negative values for X and Y in the config?

**Comment by Noaaan** [comment]
Considering it spawns exclusively in the nether, this would likely just break the ore spawning since spawning it out of world isn't possible. The only time you can have a height range outside the world is with the `trapezoid` height range (where the ores spawn more often in the middle of the range).  

Manually selecting trapezoid ores will be configurable once the next update rolls out. For now I recommend avoiding setting your ranges outside the dimensions heights.  
For Overworld this range is from -64 to 320, and for the Nether it is from 0 to 128. I am unsure what exactly it is for The End.

**Comment by itsdinkd** [comment]
Thank you for the informative answer. Looking forward to that feature, in the mean time though I will go ahead and fix that spawn range. Thanks again
