### ISSUE TITLE
Hallowed items/armor

### ISSUE THREAD

**Issue by Omegarte** [Noaaan/MythicMetals#57]
Hallowed items/armor have worse stats than Orichalcum.

**Comment by Noaaan** [comment]
If you prioritize durability it is easy to see why you would think this. 
Durability-wise Orichalcum tools are way better, and the armor has slightly more. Orichalcum also has KB resistance which Hallowed does not, because Orichalcum *is designed to make for better armor.*

Hallowed gear is balanced around the hallowed materials. It is not supposed to be a direct upgrade from all of them. In comparison to an Orichalcum Pickaxe, a Hallowed Pickaxe has less durability, but it is **much** faster and has better DPS. This goes for all Hallowed tools if you compare against Orichalcum. 

If you enjoy min-maxing then keep making Orichalcum armor. Some players might not like KB resistance and can opt out by making Hallowed Armor. 

If you believe that Orichalcum tools are better, then that is simply your preference.
