### ISSUE TITLE
Crash for some reason when forging alloy (some other mods included but im not sure if thats the problem)

### ISSUE THREAD

**Issue by Kaizuto** [Noaaan/MythicMetals#68]
https://pastebin.com/02Bms4Kw

**Comment by Noaaan** [comment]
This is an a duplicate issue (see https://github.com/LordDeatHunter/Alloy-Forgery/issues/40) with OwO([owo-lib](https://www.curseforge.com/minecraft/mc-mods/owo-lib)), which has already been fixed. If you update to the latest version then you should not crash on forging an alloy.

**Comment by Kaizuto** [comment]
But i don't even have owo-lib installed

EDIT: I added, crashed on start, i have latest mythic metal, aloy forgery and owo-lib, mc ver 1.18
https://pastebin.com/WZDGcfP6

**Comment by Noaaan** [comment]
I am sorry for telling you to get the latest version, as owo 0.5.4 (version you have installed) is for 1.18.2 only. The latest Minecraft made big breaking changes to registry, so it is not compatible.

OwO is usually included in Mythic Metals, which is why you originally did not install it yourself. The only working version that is compatible for 1.18.1 is `0.5.2`

I will fix this for 0.12.0, which is almost ready for release. This version will ship for 1.18.1, and then I will port to 1.18.2.

**Comment by Kaizuto** [comment]
OK thanks a lot
