### ISSUE TITLE
Crashes When Mining Banglum Ore. [ Fabric 0.13.3 ]

### ISSUE THREAD

**Issue by jakens1** [Noaaan/MythicMetals#71]
It seems to be crashing when I mine Banglum Ore. Using a Tech Reborn Pickaxe.

[crash-2022-03-16_21.00.51-server.txt](https://github.com/Noaaan/MythicMetals/files/8279454/crash-2022-03-16_21.00.51-server.txt)

**Comment by Noaaan** [comment]
This is a really strange issue, but I think it is due to you using Oracle Java for running your server. I used Adoptium OpenJDK 17 to compile, so it might simply not find the exact same method used for `nextFloat`.

I am already drafting up a new release, so this will likely be  changed and fixed then.

If you are able to I would ask you to try use OpenJDK to run your server and see if it changes things, as then I would be sure this is the issue
